### ISSUE TITLE
Question about Robust Clustering loss.

### ISSUE THREAD

**Issue by YangYang** [penghu-cs/MRL#2]
Sorry to bother you again. I find equation (5) in the paper is not similar to the lines 217 in /src/utils.py. Could you explain it. Thanks.

**Comment by penghu-cs** [comment]
Since ![\sum_{k=1}^{K}p(k|\mathbf{x}_{j}^{i})=1](https://latex.codecogs.com/gif.image?\dpi{80}\sum_{k=1}^{K}p(k|\mathbf{x}_{j}^{i})=1&space;), we could obtain the following equation:
![Lr](https://user-images.githubusercontent.com/45786915/123547906-37ba7e80-d795-11eb-8407-e14353fac4e3.png)
Therefore, Eq. (5) is equivalent to Line 217 in /src/utils.py. Thanks.

**Comment by YangYang** [comment]
Thanks for your reply. It's helpful.
